#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-lavacli
Version  : 1.6
Release  : 1
URL      : https://files.pythonhosted.org/packages/09/7d/a27c942dfcb19d49e9fd9bc27b143f6db6bab986fd031080e9bdb04f20c7/lavacli-1.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/09/7d/a27c942dfcb19d49e9fd9bc27b143f6db6bab986fd031080e9bdb04f20c7/lavacli-1.6.tar.gz
Summary  : LAVA XML-RPC command line interface
Group    : Development/Tools
License  : AGPL-3.0
Requires: pypi-lavacli-bin = %{version}-%{release}
Requires: pypi-lavacli-license = %{version}-%{release}
Requires: pypi-lavacli-python = %{version}-%{release}
Requires: pypi-lavacli-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(aiohttp)
BuildRequires : pypi(jinja2)
BuildRequires : pypi(pytest_runner)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(pyzmq)
BuildRequires : pypi(requests)
BuildRequires : pypi(ruamel.yaml)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package bin
Summary: bin components for the pypi-lavacli package.
Group: Binaries
Requires: pypi-lavacli-license = %{version}-%{release}

%description bin
bin components for the pypi-lavacli package.


%package license
Summary: license components for the pypi-lavacli package.
Group: Default

%description license
license components for the pypi-lavacli package.


%package python
Summary: python components for the pypi-lavacli package.
Group: Default
Requires: pypi-lavacli-python3 = %{version}-%{release}

%description python
python components for the pypi-lavacli package.


%package python3
Summary: python3 components for the pypi-lavacli package.
Group: Default
Requires: python3-core
Provides: pypi(lavacli)
Requires: pypi(aiohttp)
Requires: pypi(jinja2)
Requires: pypi(pyyaml)
Requires: pypi(pyzmq)
Requires: pypi(requests)
Requires: pypi(ruamel.yaml)

%description python3
python3 components for the pypi-lavacli package.


%prep
%setup -q -n lavacli-1.6
cd %{_builddir}/lavacli-1.6
pushd ..
cp -a lavacli-1.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679433675
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-lavacli
cp %{_builddir}/lavacli-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-lavacli/78e50e186b04c8fe1defaa098f1c192181b3d837 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lavacli

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-lavacli/78e50e186b04c8fe1defaa098f1c192181b3d837

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
